<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="drobot">

  <!-- ============================================================
       DROBOT - Drone-Rover Hybrid
       Bulnabi Software Team / SAC2026
       
       좌표 변환: SolidWorks(Y-up) → ROS(Z-up)
       어셈블리 STL에 rpy="-pi/2 0 0" 적용
       ============================================================ -->

  <xacro:include filename="$(find drobot_description)/urdf/properties.xacro"/>
  <xacro:include filename="$(find drobot_description)/urdf/materials.xacro"/>
  <xacro:include filename="$(find drobot_description)/urdf/macros.xacro"/>
  <xacro:include filename="$(find drobot_description)/urdf/gazebo.xacro"/>

  <xacro:arg name="use_sim" default="true"/>
  <xacro:arg name="use_ros2_control" default="true"/>

  <!-- ==================== BASE ==================== -->
  <link name="base_footprint"/>

  <joint name="base_footprint_joint" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link"/>
    <origin xyz="0 0 ${wheel_radius + base_height/2 + 0.05}" rpy="0 0 0"/>
  </joint>

  <link name="base_link">
    <visual>
      <!-- 어셈블리 STL → rpy로 Y-up→Z-up 변환 -->
      <origin xyz="${base_mesh_ox} ${base_mesh_oy} ${base_mesh_oz}"
              rpy="${asm_rpy}"/>
      <geometry>
        <mesh filename="package://drobot_description/meshes/base.stl"
              scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="dark_gray"/>
    </visual>
    <collision>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="${base_mass}"/>
      <xacro:box_inertia m="${base_mass}" x="${base_length}" y="${base_width}" z="${base_height}"/>
    </inertial>
  </link>

  <!-- ==================== LEFT / RIGHT ==================== -->
  <xacro:side prefix="left"  y_reflect="1"/>
  <xacro:side prefix="right" y_reflect="-1"/>

  <!-- ==================== SENSORS ==================== -->
  <xacro:sensor_mount name="lidar" parent="base_link"
                       xyz="0 0 ${base_height/2 + 0.05}" rpy="0 0 0">
    <geometry><cylinder radius="0.03" length="0.04"/></geometry>
  </xacro:sensor_mount>

  <xacro:sensor_mount name="camera" parent="base_link"
                       xyz="${base_length/2} 0 0" rpy="0 0 0">
    <geometry><box size="0.03 0.08 0.03"/></geometry>
  </xacro:sensor_mount>

  <xacro:sensor_mount name="imu" parent="base_link"
                       xyz="0 0 0" rpy="0 0 0">
    <geometry><box size="0.02 0.02 0.01"/></geometry>
  </xacro:sensor_mount>

  <!-- ==================== ROS2 CONTROL ==================== -->
  <xacro:if value="$(arg use_ros2_control)">
    <xacro:include filename="$(find drobot_description)/urdf/ros2_control.xacro"/>
  </xacro:if>

</robot>
